services:
  setup-server:
    image: nginx:1.30.0-alpine
    container_name: setup-server
    restart: unless-stopped

    ports:
      - "127.0.0.1:8085:80"

    volumes:
      - /root/setup/public:/usr/share/nginx/html:ro

    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
