services:
  bootstrap-server-sh:
    image: nginx:1.30.0-alpine
    container_name: bootstrap-server-sh
    restart: unless-stopped
    profiles: ["prod"]
    ports:
      - "8085:80"
    volumes:
      - ./public:/usr/share/nginx/html:ro
    networks:
      - proxy-network

  bootstrap-server-sh-dev:
    image: nginx:1.30.0-alpine
    container_name: bootstrap-server-sh-dev
    restart: unless-stopped
    profiles: ["dev"]
    ports:
      - "8086:80"
    volumes:
      - ./public:/usr/share/nginx/html:ro
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
